name: madot
services:
    database:
        container_name: 'madot-database'
        build:    
            context: .
            dockerfile: ./build/database.Dockerfile
            args:
                SQLPROJ_NAME: 'Madot.Database'
                DATABASE_NAME: 'Madot'
                DATABASE_SEED_DATA: 1
                DATABASE_SA_PASSWORD: 'Password123!'
        ports:
            - 1433:1433

            
            
  
