CREATE TABLE [dbo].[VersionedDocument] (
       [Id]                 AS ([ApiName] + ':' + [DocumentType] + ':' + CONVERT([VARCHAR](10),[Version])) PERSISTED NOT NULL,
       [ApiName]            VARCHAR(50)  NOT NULL,
       [DocumentType]       VARCHAR(20)  NOT NULL,
       [IsAutogenerated]    BIT          NOT NULL,
       [Version]            INT          NOT NULL,
       [FileTypeExtension]  VARCHAR(5)   NOT NULL,
       [IsLatest]           BIT          NOT NULL,
       [Data]               VARCHAR(MAX) NOT NULL,
       [CreatedDate]        DATETIME2(7) CONSTRAINT [DF_VersionedDocument_CreatedDate] DEFAULT ((GETUTCDATE())) NOT NULL,
       [CreatedBy]          VARCHAR(100) NULL
       CONSTRAINT [PK_VersionedDocument] PRIMARY KEY CLUSTERED ([Id]),
       CONSTRAINT [FK_VersionedDocument_Api] FOREIGN KEY ([ApiName]) REFERENCES [dbo].[Api] ([Name]),
       CONSTRAINT [UC_VersionedDocument] UNIQUE ([ApiName],[DocumentType],[Version],[IsAutogenerated]),
       CONSTRAINT [CC_VersionedDocument_Type] CHECK ([DocumentType]='OpenApiSpec' OR [DocumentType]='Documentation'),
       CONSTRAINT [CC_VersionedDocument_Version] CHECK ([Version]>0),
       CONSTRAINT [CC_VersionedDocument_FileTypeExtension] CHECK ([FileTypeExtension] = 'json' OR [FileTypeExtension] = 'yml' OR [FileTypeExtension] = 'yaml' OR [FileTypeExtension] = 'md'),
       INDEX [IX_VersionedDocument_Latest] UNIQUE NONCLUSTERED ([ApiName],[DocumentType],[IsAutogenerated]) WHERE [IsLatest] = 1
);
